version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
      - ./media:/vol/web/media
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8080"
    env_file:
      - .env
    depends_on:
      - db

  db:
    container_name: db-planetarium
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - db-planetarium-volume:/var/lib/postgresql/data/

volumes:
  db-planetarium-volume:
    driver: local
