# Generated by Django 4.2.4 on 2023-08-13 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planetarium", "0004_alter_ticket_options_astronomyshow_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="astronomyshow",
            name="show_themes",
            field=models.ManyToManyField(blank=True, to="planetarium.showtheme"),
        ),
    ]
