# Generated by Django 4.2.4 on 2023-08-24 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("planetarium", "0005_alter_astronomyshow_show_themes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="astronomyshow",
            name="show_themes",
            field=models.ManyToManyField(
                blank=True, related_name="astronomy_shows", to="planetarium.showtheme"
            ),
        ),
        migrations.AlterField(
            model_name="showsession",
            name="planetarium_dome",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="show_sessions",
                to="planetarium.planetariumdome",
            ),
        ),
    ]
